_target_: neuralop.models.gino.GINO

in_channels: 3 # G
out_channels: 1  # G
res: False # TODO: This is always ignored in GINO from neural operator!
gno_coord_dim: 2 # G
gno_embed_channels: 32 # G
gno_embed_max_positions: 600 # G
gno_weight_function_scale: 0.0306249
in_gno_pos_embed_type: None
out_gno_pos_embed_type: None
gno_weighting_function: half_cos 
gno_reduction: mean
gno_use_open3d: False
in_gno_radius: 0.16 # G TODO: Change the name
out_gno_radius: 0.175 # G
in_gno_transform_type: linear # G
out_gno_transform_type: linear # G
in_gno_channel_mlp_hidden_layers :  [4, 256, 512, 256, 3] # G
out_gno_channel_mlp_hidden_layers :  [128, 512, 1024, 512, 64] # G
# in_gno_tanh: config.gino.in_gno_tanh # TODO: Remove this as this is not used!
in_gno_tanh: None
out_gno_tanh: None # G
fno_n_modes: [20, 20] # G
fno_hidden_channels: 64 # G
fno_lifting_channel_ratio: 4
fno_n_layers: 2 # G
fno_use_channel_mlp: True # TODO: Change the name
fno_norm: group_norm # G
fno_ada_in_features: 8 # G
fno_rank: 0.8 # G
fno_domain_padding: 0.0 # TODO: This is ignored in GINO from neural operator library
fno_channel_mlp_expansion: 0.5
projection_channel_ratio: 4