_target_: neuralop.models.gino.GINO

in_channels: 5 # G
out_channels: 1  # G
gno_coord_dim: 3 # G
gno_embed_channels: 16 # G
gno_embed_max_positions: 600 # G
gno_use_open3d: False
in_gno_radius: 0.04 # G TODO: Change the name
out_gno_radius: 0.04 # G
in_gno_transform_type: linear # G
out_gno_transform_type: linear # G
in_gno_channel_mlp_hidden_layers :  [80, 80, 80] # G
out_gno_channel_mlp_hidden_layers :  [512, 256] # G
# in_gno_tanh: config.gino.in_gno_tanh # TODO: Remove this as this is not used!
out_gno_tanh: None # G
fno_n_modes: [15, 15, 15] # G
fno_hidden_channels: 64 # G
fno_lifting_channel_ratio: 4    # 64 * 4 = 256 (Matches original)
projection_channel_ratio: 4     # 64 * 4 = 256 (Matches original - WAS 1)
fno_n_layers: 2 # G
fno_use_channel_mlp: True # TODO: Change the name
fno_norm: group_norm # G
fno_ada_in_features: 8 # G
fno_rank: 0.8 # G
fno_channel_mlp_expansion: 0.5
fno_in_channels: 5
